### PR TITLE
(fix) nx project name

### PR DESCRIPTION
**Pull request by excalios**
NX  was using base project as project name. This PR changes the project name to the correct one.
Fixed by @perfectspr referenced in #633 

Make sure these boxes are checked before submitting your pull request:

- [ ] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

I don't think the README nor Vim documentation needs to be updated. For the spec I'm not sure on how to update it.

### CODE REVIEW

**Comment by codeinabox** [comment]
> For the spec I'm not sure on how to update it.

Thank you for this addition and your patience for it to be reviewed. This looks great however I'd like to have a spec to deal with this scenario, happy to write this for you if you give me write access to your branch.

**Comment by codeinabox** [comment]
Keen to get this merged but I want a spec for it. I've tried adding one but I am not sure on an example, so could you please help with this.

**Comment by codeinabox** [comment]
Happy new year! Following this up as I'm keen to get it merged in, so let me know if you need a hand writing the spec

**Comment by excalios** [comment]
Hello! sorry for the late reply. Yes!! help with writing the spec would be highly appreciated.

There is another problem though besides the nx wasn't able to find the correct project name. Now with the current nx version the structure of the nx project has changed to the point vim-test doesn't even detect the project anymore. Since now the project is only defined in the `project.json` in each project but there is no more in the root folder. Hence, making the test won't run at all since they can't find the project name. Currently, I have no solution for this problem though so far I just ran my test manually unfortunately.

**Comment by excalios** [comment]
Hello, I'm back to this issue to mention I just tried to fix/adjust the test function for nx to adjust to the newest Nx structure which is using `project.json`. I'm still unsure about creating the spec file for the PR. I also didn't cover if we have a different nx version that is still using `workspace.json`. So, I'll just share the changes I made so other people that have the same experience as mine can adjust their code.

File: `autoload/test/javascript/nx.vim`

```vim
function! test#javascript#nx#build_position(type, position) abort
  let l:path = split(a:position['file'], '/')[0:-2]
  while len(path) > 0
    if filereadable(join(path, '/')."/project.json")
      let l:workspaces = readfile(join(path, '/')."/project.json")
      if exists('*json_decode')
        let l:name = json_decode(join(workspaces, ''))['name']
        let project = name
        break
      endif
    endif
    let path = path[0:-2]
  endwhile

  if a:type ==# 'nearest'
    let name = s:nearest_test(a:position)
    if !empty(name)
      let name = '-t '.shellescape(name, 1)
    endif
    return [project, name, '--test-file', a:position['file']]
  elseif a:type ==# 'file'
    return [project, '--test-file', a:position['file']]
  else
    return [project] " This will run the test for the project
  endif
endfunction
```

**Review by codeinabox — CHANGES_REQUESTED** [review]
Thank you for getting back in touch, could you please update `spec/fixtures/nx/workspace.json` with an example that you developed against

**Comment by excalios** [comment]
Sure! I'll try it in my spare time maybe over the weekend. I'll create a new PR later and I'll contact if I need any help

**Comment by codeinabox** [comment]
> Sure! I'll try it in my spare time maybe over the weekend. I'll create a new PR later and I'll contact if I need any help

Thank you! No need to create a new PR, you could update this one

**Comment by codeinabox** [comment]
Closing this as  #760, an implementation with fixtures, has been merged in

**Pull request closed without merging**
