### PR TITLE
feat: pytest import detection

### PR DESCRIPTION
**Pull request by codeinabox**
Make sure these boxes are checked before submitting your pull request:

- [ ] Add fixtures and spec when implementing or updating a test runner
- [ ] Update the README accordingly
- [ ] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by matt-gardner** [comment]
After this commit, I ran into consistent errors with `Not a test file`, where before this commit it was working just fine.  The issue is that it's not uncommon to have tests that are run with `pytest` that don't import `pytest` anywhere in the file, so the check implemented in this PR makes things that were previously working fail.  It took me a fair amount of digging to track down why my tests would no longer run to this PR.

Overall I think it's not unreasonable to have the default behavior be to not run a test if there's no runner set and you can't unambiguously determine what runner to use.  But the error message was "Not a test file", which is wrong, and the language-specific documentation for python says "By default the first available will be chosen", which is no longer true.

If it's more helpful to open this as an issue instead of putting it as a comment here, I can do that too.

**Comment by codeinabox** [comment]
> After this commit, I ran into consistent errors with `Not a test file`, where before this commit it was working just fine.  The issue is that it's not uncommon to have tests that are run with `pytest` that don't import `pytest` anywhere in the file, so the check implemented in this PR makes things that were previously working fail.  It took me a fair amount of digging to track down why my tests would no longer run to this PR.
> 
> Overall I think it's not unreasonable to have the default behavior be to not run a test if there's no runner set and you can't unambiguously determine what runner to use.  But the error message was "Not a test file", which is wrong, and the language-specific documentation for python says "By default the first available will be chosen", which is no longer true.
> 
> If it's more helpful to open this as an issue instead of putting it as a comment here, I can do that too.

Thank you for reporting this. Does your project have a pytest.ini file? It's on my to do list to use it to determine the runner.

**Comment by matt-gardner** [comment]
We don't have a `pytest.ini` file, but we do have a `[tool.pytest.ini_options]` section in our `pyproject.toml`.

**Comment by codeinabox** [comment]
> We don't have a `pytest.ini` file, but we do have a `[tool.pytest.ini_options]` section in our `pyproject.toml`.

@matt-gardner not forgotten about this, just been busy. In the interim, you should be able to use `g:test#python#runner`

**Comment by matt-gardner** [comment]
@codeinabox no worries, nothing's blocking me, I did the `g:test#python#runner` fix before ever commenting here.  I was just giving a heads up about the confusion, as it took me a while to figure out that that was the right fix and trace it here.

**Pull request merged**
