### PR TITLE
Initial approach for integration tests in maven.

### PR DESCRIPTION
**Pull request by Tacsiazuma**
Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by codeinabox** [comment]
Do you need a hand finishing off this pull request or should we close this?

**Comment by Tacsiazuma** [comment]
@codeinabox sorry for the delay. I already started implementing this and its working for me, just forgot to push the changes.

**Comment by Tacsiazuma** [comment]
@codeinabox had a chance to review it?

**Review by codeinabox — COMMENTED** [review]
Thank you for this! LGTM though could add the documentation also to `doc/test.txt`

**Comment by Tacsiazuma** [comment]
@codeinabox added doc/test.txt part as well.

**Review by codeinabox — APPROVED** [review]
Thank you for this and your patience with the time it took me to review it.

**Pull request merged**
