### PR TITLE
 (fix) Nested tests fail in Java JUnit #627 

### PR DESCRIPTION
**Pull request by GiuseppeMP**
Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner - added new fixture of java with junit5 + gradle
- [x] Update the README accordingly (no needed)
- [x] Update the Vim documentation in `doc/test.txt` (no needed)

### CODE REVIEW

**Comment by GiuseppeMP** [comment]
- More tests needed.
- Missing maven support.

**Comment by GiuseppeMP** [comment]
I trying to understand why the :UltestNearest worked well and the :TestNearest doesn't.

image

Any thoughts?

**Comment by GiuseppeMP** [comment]
> I trying to understand why the :UltestNearest worked well and the :TestNearest doesn't.
> 
> image
> 
> Any thoughts?

Resolved in the last commit.

**Comment by GiuseppeMP** [comment]
The issue #621 was also resolved in this pull request.

**Comment by GiuseppeMP** [comment]
@codeinabox is there any updates?

**Comment by codeinabox** [comment]
Thank you for your contribution and patience, this all looks good to me so I am happy to merge in though are you still having issues with `TestNearest`?

**Comment by GiuseppeMP** [comment]
> 

Hey,
`TestNearest` for java maven and java gradle projects are working fine ✌🏾 

I also resolved the #621 in this pull request.

**Review by codeinabox — APPROVED** [review]
Massive gratitude for all your hard work on this!

**Pull request merged**
