### PR TITLE
Allow configuring stack test command

### PR DESCRIPTION
**Pull request by drewolson**
This PR allows overriding the test command for Haskell's `stack`. Specifically, it allows you to use `test .` as the default command, which works better in multi-package stack projects.

### CODE REVIEW

**Review by codeinabox — COMMENTED** [review]
Thank you for this. There is a failing test in spec/stacktest_spec.vim, let me know if you need a hand updating this.

**Comment by drewolson** [comment]
Whoops sorry about that, I'll take a look now.

**Comment by drewolson** [comment]
I'm actually not sure why `"test"` was quoted only in the zero-argument case. I think this is incorrect. Are you ok with me updating this test to remove the quotes?

**Comment by drewolson** [comment]
I've updated the test, let me know if this works for you.

**Comment by codeinabox** [comment]
> I've updated the test, let me know if this works for you.

Thank you for quickly sorting this. Could you please  add a scenario to the spec where `g:test#haskell#stacktest#test_command` is overriden and then I think this is good to merge in.

**Comment by drewolson** [comment]
@codeinabox done

**Review by codeinabox — APPROVED** [review]
Thanks again, this is great and I'm happy to merge it in

**Pull request merged**
