### PR TITLE
Gradle multi module support

### PR DESCRIPTION
**Pull request by Tacsiazuma**
Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by codeinabox** [comment]
Thank you for this, I will review this soon. In the mean time could you merge in or rebase against master as I've fixed the build issues.

**Comment by Tacsiazuma** [comment]
@codeinabox done. Can you also check #494? Both solution is kinda similar.

**Comment by Tacsiazuma** [comment]
@codeinabox removed the generated and misc files.

**Comment by Tacsiazuma** [comment]
@codeinabox can you check it again and merge if its still OK?

**Pull request merged**
