### PR TITLE
Added test suite method pattern

### PR DESCRIPTION
**Pull request by mats852**
Test suites such as stretchr/testify uses methods as test functions

Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Comment by codeinabox** [comment]
Let me know if you'd like a hand with this, particularly updating the fixtures and spec

**Comment by mats852** [comment]
> Let me know if you'd like a hand with this, particularly updating the fixtures and spec

Hi @codeinabox!

I had started the modifications via my web browser but I'll finish the work locally on my computer :)

One question though, should I add this case to `gotest`, for example the fixture [/spec/fixtures/gotest/normal_test.go](https://github.com/vim-test/vim-test/blob/master/spec/fixtures/gotest/normal_test.go)?

Thanks

**Comment by codeinabox** [comment]
> One question though, should I add this case to `gotest`, for example the fixture [/spec/fixtures/gotest/normal_test.go](https://github.com/vim-test/vim-test/blob/master/spec/fixtures/gotest/normal_test.go)?

That's right, you'd either modify or add a new example in `/spec/fixtures/gotest/`

**Comment by mats852** [comment]
> > One question though, should I add this case to `gotest`, for example the fixture [/spec/fixtures/gotest/normal_test.go](https://github.com/vim-test/vim-test/blob/master/spec/fixtures/gotest/normal_test.go)?
> 
> That's right, you'd either modify or add a new example in `/spec/fixtures/gotest/`

Great, I'll get that done throughout the day. Thanks!

**Comment by mats852** [comment]
Sorry I renamed my branch and it closed on github. I'll proceed with this poorly named branch 😅

**Comment by mats852** [comment]
This PR should solve issue https://github.com/vim-test/vim-test/issues/624

**Comment by lourenci** [comment]
Hey, @mats852. Author of #624 here: it didn't fix that issue 😢.

To be honest, this PR caused an issue that you're not able to run nearest tests anymore when they are using the [testify suite](https://github.com/stretchr/testify#suite-package) feature.

`some_test.go`
```go
import (
	"github.com/stretchr/testify/suite"
)

type ExampleTestSuite struct {
	suite.Suite
	VariableThatShouldStartAtFive int
}

func (suite *ExampleTestSuite) SetupTest() {
	suite.VariableThatShouldStartAtFive = 5
}

func (suite *ExampleTestSuite) TestExample() {
	suite.Equal(suite.VariableThatShouldStartAtFive, 5)
}
```

Cursor nearest to `TestExample`, this is how `vim-test` is running after this PR:
`go test -run 'TestExample$' ./package # go is not finding any test to run`

Cursor nearest to `TestExample`, this is how `vim-test` is suppose to run with the testify suite:
`go test -run ExampleTestSuite ./package -testify.m TestExample`

**Comment by codeinabox** [comment]
> Cursor nearest to `TestExample`, this is how `vim-test` is running after this PR: `go test -run 'TestExample$' ./package # go is not finding any test to run`
> 
> Cursor nearest to `TestExample`, this is how `vim-test` is suppose to run with the testify suite: `go test -run ^TestSuiteTests$ ./package -testify.m ^TestExample$`

Thank you for these examples, we could feed these back into the specs and fixtures to fix this issue.

**Comment by lourenci** [comment]
Sorry for not providing any more help on that. On 20 Sep 2022, at 7:43 pm, Mathew Attlee ***@***.***> wrote:﻿

Cursor nearest to TestExample, this is how vim-test is running after this PR: go test -run 'TestExample$' ./package # go is not finding any test to run
Cursor nearest to TestExample, this is how vim-test is suppose to run with the testify suite: go test -run ^TestSuiteTests$ ./package -testify.m ^TestExample$

Thank you for these examples, we could feed these back into the specs and fixtures to fix this issue.

**Comment by yshadow** [comment]
Hello guys, this plugin is great I'm using it for table based tests, but as it already being said - it doesn't work for suite of tests. Calling :TestNearest gives you just:
testing: warning: no tests to run
PASS

**Pull request merged**
