### PR TITLE
TestNearest support in "denotest"

### PR DESCRIPTION
**Pull request by yaegassy**
## Description

The current `denotest` only seems to support `:TestFile`, so I added support for `:TestNearest`.

## DEMO

denotest-nearest

### CODE REVIEW

**Review by codeinabox — COMMENTED** [review]
This is a great addition thank you! Could we add some specs and I am happy to merge this in

**Comment by yaegassy** [comment]
Thanks for reviewing. 🙇

I don't use ruby, so I don't have the ruby environment in place, and it will take some time to create the vim-test tests. :(

**Comment by yaegassy** [comment]
`vim-flavor` test has been added. 🙇

**Review by codeinabox — APPROVED** [review]
Looks great and thank you for taking the time to write the specs

**Comment by yaegassy** [comment]
Thanks Marge!

**Pull request merged**
