### PR TITLE
Add pipenv and poetry check to djangotest

### PR DESCRIPTION
**Pull request by hdra**
Make sure these boxes are checked before submitting your pull request:

- [ x] Add fixtures and spec when implementing or updating a test runner
- [ x] Update the README accordingly
- [ x] Update the Vim documentation in `doc/test.txt`

### CODE REVIEW

**Review by codeinabox — COMMENTED** [review]
Thank you for this, looks great. We should add some specs for this scenario, happy to help with that

**Comment by hdra** [comment]
Updated with the spec, though I have to admit I'm going to be relying on some kind of CI test runner here coz I can't take the detour to setup ruby atm

**Comment by malkoG** [comment]
Is there any updates?

**Review by codeinabox — APPROVED** [review]
This looks great, thanks again and apologies this slipped off my radar 😅

**Pull request merged**
