### PR TITLE
Update PyUnitTest to use Python3

### PR DESCRIPTION
**Pull request by fdelacruz**
Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner

### CODE REVIEW

**Comment by fdelacruz** [comment]
These tests are failing because the "Actual value" has python. Even if, for whatever reason, this PR is not accepted. Can that be changed?
Screen Shot 2021-01-20 at 3 04 22 PM

**Comment by codeinabox** [comment]
Thank you for this PR, could you include the changes from #543 and that will make the tests in this PR pass

**Comment by fdelacruz** [comment]
These tests fail because they seem to be fixated to use python not python3. I don't see where is that setup, its not in the .travis.yml

**Comment by fdelacruz** [comment]
These tests fail because they seem to be set to use python not python3. I don't see where is that configured, since it's not in the .travis.yml

**Pull request closed without merging**
